config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'team', to: 'static_pages#team'
  get 'contact', to: 'static_pages#contact'

  get    '/signup', to: 'users#new'
  post   '/signup', to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :sessions
  resources :gossips
  resources :comments
  resources :likes

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
  has_many :likes, as: :likeable
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  has_many :comments
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :tags, through: :tag_gossips
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossips, through: :tag_gossips 
end

app/models/tag_gossip.rb
class TagGossip < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/user.rb
class User < ApplicationRecord
  has_many :gossips, dependent: :destroy
  has_many :comments
  has_many :likes, dependent: :destroy

  before_save { self.email = email.downcase }
  validates :username, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @user = User.find(params[:user_id])
    @gossip = Gossip.find(params[:gossip_id])
  end

  def create
    @comment = Comment.create!(user_id: session[:user_id], gossip_id: @gossip.id, content: params[:comment][:content])
    @comment.gossip_id = params[:gossip_id]
    redirect_to "/users/#{session[:user_id]}/gossips/#{@gossip.id}"
  end

  def edit
    @gossip = Gossip.find(params[:id])
    @comment = Comment.find(params[:id])
  end

 def update
   @comment = Comment.find(params[:id])
   @comment.update(comment_params)
  redirect_to "/users/#{session[:user_id]}/gossips/#{@gossip.id}"
 end

 def destroy
   @comment = Comment.find(params[:id])
   @comment.delete
   redirect_to "/users/#{session[:user_id]}/gossips/#{@gossip.id}"
 end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def index
    @gossip = Gossip.all
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.create!(user_id: session[:user_id], content: params[:gossip][:content], title: params[:gossip][:title])
    flash[:success] = "Created !"
    redirect_to "/gossips"
  end

  def gossip_params
    params.require(:gossip).permit(:title, :content)
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comment = Comment.new
    @comment.gossip_id = @gossip.id
  end

  def edit
    @user = User.find(params[:id])
    @gossip = Gossip.find(params[:id])
    redirect_to "/gossips"
  end

  def update
    @gossip = Gossip.find(params[:id])
    gossip_params = params.require(:gossip).permit(:title, :content, :user_id)
    @gossip.update(gossip_params)
    flash[:success] = "Updated !"
    redirect_to "/users/#{session[:user_id]}/gossips/"
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.delete
    flash[:danger] = "Deleted"
    redirect_to "/gossips"
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_gossip
  before_action :find_like, only: [:destroy]

  def new
    @like = Like.new
    if  Like.find_by(user_id: session[:user_id])
     destroy
    else
      create
    end
  end

  def create
    Like.create!(user_id: session[:user_id], likeable_id: params[:gossip_id], likeable_type: "Gossip")
    #@gossip.likes.create(user_id: current_user.id)
    redirect_to gossip_path
  end

  def find_gossip
    @gossip = Gossip.find(params[:gossip_id])
  end

  def destroy
    if !(already_liked?)
    flash[:notice] = "Cannot unlike"
  else
    @like.destroy
  end
  redirect_to gossip_path(@gossip)
  end

  def find_like
   @like = @gossip.likes.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "Logged in"
      log_in user #use method from helpers - temporary cookie
      redirect_to '/'
    else
       flash[:danger] = 'Invalid email or password combination'
      render 'new'
    end
  end

    def destroy
      log_out if logged_in? #method from helpers
      flash[:success] = 'Logged out'
      redirect_to '/'
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def team
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params_users)
    if @user.save
    flash[:success] = "Successfully created on website!"
    redirect_to '/'
    else
    flash[:danger] = "Error"
    render 'new'
    end
  end

  private
  def params_users
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  #temporary session cookie when log in - expires when browser closed
  def log_in(user)
    session[:user_id] = user.id
  end

  #temporary session cookie -> applicate current_user session on subsequent pages
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  #Returns true if user logged in, false otherwise (show link log out if true)
  def logged_in?
    !current_user.nil?
  end

  #log out delete session -> current user = nil
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/edit.html.erb
<h1 class="title">Rectification</h1>

<div class="formulaire">
<%= form_for [@gossip, @comment] do |f| %>
  <p>Updated  : <br> <%= f.text_area :content %></p>
  <p>By : <br> <%= f.text_field :anonymous_commentor %></p>
  <%= f.submit %>
<% end %>
</div>

app/views/comments/update.html.erb
<p>Ok!</p>

app/views/gossips/_comment.html.erb
<div class="card-comment">
<div class="card w-50">
  <div class="card-body">
    <h5 class="card-title"><%= comment.anonymous_commentor %></h5>
    <p class="card-text"><%= comment.content %></p>
    <p><%= comment.created_at %><p>
    <p><%= comment.updated_at %><p>
    <a href="<%= edit_user_gossip_comment_path(@gossip.id, comment.id)%>" class="btn btn-primary">Edit</a>
    <a href="<%= user_gossip_comment_path(@gossip.id,comment.id)%>" class="btn btn-danger" data-confirm="Are you sure ?" data-method="DELETE">Delete</a>
  </div>
</div>
</div>
<br>

app/views/gossips/edit.html.erb
<% if logged_in? %>

<h1 class="title">Rectification</h1>

<div class="formulaire">
<%= form_for @gossip do |f| %>
  <p>Updated title : <br> <%= f.text_field :title%></p>
  <p>Updated  : <br> <%= f.text_area :content %></p>
  <%= f.submit %>
<% end %>
</div>

<%else%>

<p> Can't edit without sign </p>

<%end%>

app/views/gossips/index.html.erb
<% if logged_in? %>

<h1 class="title">Latest Gossips</h1>

<% @gossip.each do |gossip, index| %>
<div class="cardbox">
<div class="card border-light mb-3" style="max-width: 18rem;">
  <div class="card-header"><a href="/gossips/<%=gossip.id%>" class="linko">Gossip n°<%= gossip.id%></a></div>
  <div class="card-body">
    <h5 class="card-title"><%= gossip.title %></h5>
    <p class="card-text"><%= gossip.content%></p>
    <p class="card-text"><%= gossip.anonymous_gossiper%></p>
  </div>
</div>
</div>
<% end %>

<%end%>

app/views/gossips/new.html.erb
<% if logged_in? %>

<h1 class="title">Tell me</h1>

<%= form_for @gossip, url: {action: "create"} do |f| %>
<div class="form-group">
    <%= f.text_field :title, placeholder: 'Title', class: "form-control" %>
</div>
<div class="form-group">
<%= f.text_area :content, placeholder: 'Gossip', class: "form-control" %>
</div>
<div class="form-group">
    <button class ="btn btn-outline-dark" type="submit">Create</button>
</div>
<% end %>

<%else%>

<p> If you want to write a gossip, sign now ! </p>

<%end%>

app/views/gossips/show.html.erb
<% if logged_in? %>

<div class="cardbox">
<div class="card border-light mb-3" style="max-width: 18rem;">
  <div class="card-header">Gossip n°<%= @gossip.id%></div>
  <div class="card-body">
    <h5 class="card-title"><%= @gossip.title %></h5>
    <p class="card-text"><%= @gossip.content%></p>
    <p class="card-text"><%= @gossip.anonymous_gossiper%></p>
    <p class="card-time"><%= @gossip.created_at%></p>
    <p class="card-time"><%= @gossip.updated_at %></p>
    <p>Comments (<%= @gossip.comments.size %>)</p>
    <p><%= @gossip.likes.count %> <%= (@gossip.likes.count) == 1 ? 'Like' : 'Likes'%></p>
    <a href="/users/<%=current_user.id%>/gossips/<%=@gossip.id%>/edit" class="btn btn-primary">Edit</a>
    <a href="<%=user_gossip_path(session[:user_id], @gossip.id)%>" class="btn btn-danger" data-confirm="Are you sure ?" data-method="DELETE">Delete</a>
  </div>
</div>
</div>
<p class="backhome"><a href="/">🔙</a></p>

<h1 class="title">Comments</h1>

<%= render partial: 'gossips/comment', collection: @gossip.comments.reverse %>
<!-- Display les commentaires depuis mon partial _comment.html.erb depuis la collection @gossip.comments
le reverse est pour faire du plus récent au plus ancien -->


<h1 class="title">Add a comment</h1>

<%= render partial: 'layouts/form' %> <!-- Mon formulaire pour ajouter un comment -->

<% else %>

<p> Need to sign if you want to check this out </p>

<%end%>

app/views/gossips/update.html.erb
<h1 class="title">C'est modifié</h1>

app/views/static_pages/contact.html.erb
<h1 class="title">Contact 🔥</h1>
<p>Any problem ? Go <a href="https://github.com/THP-nice">here</a> and leave a message</p>

app/views/static_pages/home.html.erb
<h1 class="title">The Gossip Project</h1>

<div class="welcome">Hello</div></p>

app/views/static_pages/team.html.erb
<h1 class="title">Nice team</h1>
<p>Gossip website made with l❤️ve by :</p>
<p><a href="https://github.com/Ysalien">👸</a> Ysaline</p>
<p><a href="https://github.com/TomacTh">👨‍💻</a> Thomas</p>
<p><a href="https://github.com/Nikitavasilev">👨‍💻</a> Nikita</p>
<p><a href="https://github.com/Natdenice">👨‍💻</a> Nathaniel</p>
<p><a href="https://github.com/Tutus06">👨‍💻</a> Arthur</p>

app/views/users/new.html.erb
<h1>Sign up</h1>

<h2 class="text-center margin-header">Create a new user :</h2>
<div class="container margin-header">
	<%= form_for(@user, url: signup_path) do |f| %>
		<strong><%= f.label :username %></strong><br>
		<%= f.text_field :username, placeholder: "Your name" %><br><br>
		<strong><%= f.label :email %></strong><br>
		<%= f.email_field :email, placeholder: "Your email" %><br><br>
    <strong><%= f.label :password %></strong><br>
		<%= f.password_field :password, placeholder: "Your password" %><br><br>
		<strong><%= f.label :password_confirmation %></strong><br>
		<%= f.password_field :password_confirmation, placeholder: "Confirm your password", size: "60x10" %><br><br>
		<%= f.submit "Submit" %>
	<% end %>
</div>

<a href="/">Back</a>